import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { fetchData } from '@/app/lib/fetchData';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const data = await fetchData({}, "?page=4");
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>Root Layout:</div>
        <div>{data}</div>
        {children}
      </body>
    </html>
  );
}
