import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { fetchData } from '@/app/lib/fetchData';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function DashBoardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const data = await fetchData({next: {revalidate: 5}});
  return (
    <div>
      <h1>Dashboard Layout: </h1>
      {data}
      {children}
    </div>
  );
}
